"""Add memory_records table

Revision ID: d19e184d51a7
Revises: ae97b3b3407f
Create Date: 2026-08-06 17:16:57.450139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd19e184d51a7'
down_revision: Union[str, None] = 'ae97b3b3407f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_identifier'), 'memory_records', ['identifier'], unique=False)
    op.create_index(op.f('ix_memory_records_scope'), 'memory_records', ['scope'], unique=False)
    op.create_index('ix_memory_records_scope_identifier', 'memory_records', ['scope', 'identifier'], unique=True)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_sources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('knowledge_sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('ix_memory_records_scope_identifier', table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_scope'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_identifier'), table_name='memory_records')
    op.drop_table('memory_records')
    # ### end Alembic commands ###
