"""Add approval_requests table

Revision ID: c1a4a24108bf
Revises: d19e184d51a7
Create Date: 2026-08-06 17:19:34.824206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a4a24108bf'
down_revision: Union[str, None] = 'd19e184d51a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('requires_reason', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_reason', sa.String(length=1000), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_execution_id'), 'approval_requests', ['execution_id'], unique=False)
    op.create_index('ix_approval_requests_execution_status', 'approval_requests', ['execution_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index('ix_approval_requests_execution_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_execution_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
