"""Add metadata_json to KnowledgeSource

Revision ID: ae97b3b3407f
Revises: 5b697a6d342c
Create Date: 2026-07-29 13:42:29.294776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae97b3b3407f'
down_revision: Union[str, None] = '5b697a6d342c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_sources', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sources', 'metadata_json')
    # ### end Alembic commands ###
